### ISSUE TITLE
XTMF 1.5 Feature Brainstorm

### ISSUE THREAD

**Issue by JamesVaughan** [TravelModellingGroup/XTMF#77]
The current features being considered for the XTMF 1.5 are:

* [x] Ability to display modules that are required and have not been assigned a module. #70 
* [x] Module reordering by mouse for the GUI #37 
* [ ] <del>Exporting a module system for a previous version of XTMF #72 </del>
* [x] Upgraded save file format so each model system is by itself #73 
* [x] Ability to group a section of a list of modules into a "region" #9 
* [x] Add time of messages to console #78 
* [x] Allow mirroring of console messages to file. #78 
* [x] Allow Queued runs to be reordered #79 
* [x] Create an exclude list for module dlls #80 
* [ ] <del>Migrate all EMME Modules to TMG.EMME #81</del> 
* [x] Allow Markup for modules to direct to web documentation #87 

Other tasks that need to be complete:

* [ ] Remove Dead Code #75 
* [ ] <del>Create a diagram of the current XTMF architecture #76 </del>

Please comment below to add more ideas.

**Comment by PeterKucirek** [comment]
I really like idea of "regions", since large model systems are difficult to navigate. Some other ideas:

- Some kind of "navigation pane" that shows a "zoomed out" view of larger model systems. This would work really well with regions.
- User comments/metadata: could be attached to module parameters, modules, and regions. This allows for reminders, explanations of model design, and other things.
